service: api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: build/index.handler
    events:
      - httpApi:
          path: /
          method: get
