service: api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    KEY_ID: ${env:KEY_ID}
    ACCESS_KEY: ${env:ACCESS_KEY}
    REGION: ${env:REGION}
    BUCKET: ${env:BUCKET}

functions:
  api:
    handler: build/index.handler
    events:
      - httpApi: '*'

package:
  patterns:
    - '!node_modules/**'
    - '!src/**'
    - '!notes/**'
    - '!Dockerfile'
    - '!makefile'
    - '!package**'
    - '!**.ts'
    - '!nodemon.json'
    - '!README.md'
    - '!tsconfig.json'
    - 'build'
