name: Deploy ELB
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4

      - name: Prepare artifact
        run: zip -r deploy.zip Dockerfile src .env index.ts package.json package-lock.json tsconfig.json

      - name: Deploy to AWS ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.AWS_APP_NAME }}
          environment_name: ${{ env.AWS_ENV_NAME }}
          region: ap-southeast-1
          deployment_package: deploy.zip
          version_label: ${{github.run_number}}
